spring:
  application:
    name: api-composer

  data:
    mongodb:
      uri: mongodb://admin:admin123@localhost:27017/composed_data?authSource=admin&retryWrites=true&w=majority

  kafka:
    bootstrap-servers: localhost:29092
    consumer:
      group-id: apiComposerGroup

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    eureka-server-port: 8761
    register-with-eureka: true
    fetch-registry: true
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka

jwt:
  issuer: auth-service
  secret_key: cPlFdV3BdHxqABIwNpgvyOkZgskfj23jeJNxjujgQoE=