server:
  port: 8089

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    eureka-server-port: 8761
    healthcheck:
      enabled: true
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka
  instance:
    prefer-ip-address: true

spring:
  application:
    name: api-gateway-service

#  config:
#    import: "optional:configserver:"
#  cloud:
#    gateway:
##      httpclient:
##        connect-timeout: 10000
##        response-timeout: 10s
#      routes:
#        - id: item-service
#          uri: lb://ITEM-SERVICE
#          predicates:
#            - Path=/item-api/**
#          filters:
#            - RewritePath=/item-api/?(?<segment>.*), /$\{segment}
#            - name: CircuitBreaker
#              args:
#                name: itemCircuitBreaker
#                fallbackUri: forward:/fallback
##          metadata:
##            connect-timeout: 10000
##            response-timeout: 10000
#        - id: order-service
#          uri: lb://ORDER-SERVICE
#          predicates:
#            - Path=/order-api/**
#          filters:
#            - RewritePath=/order-api/?(?<segment>.*), /$\{segment}
#            - name: CircuitBreaker
#              args:
#                name: orderCircuitBreaker
#                fallbackUri: forward:/fallback
#        - id: auth-service
#          uri: lb://AUTH-SERVICE
#          predicates:
#            - Path=/auth-api/**
#          filters:
#            - RewritePath=/auth-api/?(?<segment>.*), /$\{segment}

resilience4j:
  timelimiter:
    configs:
      default:
        timeout-duration: 10s
        cancel-running-future: false
  circuitbreaker:
    configs:
      default:
        register-health-indicator: true
        allow-health-indicator-to-fail: false
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 10
        failure-rate-threshold: 50
        slow-call-rate-threshold: 50
        slow-call-duration-threshold: 8s
        wait-duration-in-open-state: 10s
        automatic-transition-from-open-to-half-open-enabled: false
        permitted-number-of-calls-in-half-open-state: 5
        record-exceptions:
          - java.util.concurrent.TimeoutException
          - org.springframework.cloud.gateway.support.NotFoundException
          - io.github.resilience4j.circuitbreaker.CallNotPermittedException
    instances:
      itemCircuitBreaker:
        base-config: default
        failure-rate-threshold: 50
      orderCircuitBreaker:
        baseConfig: default
        failure-rate-threshold: 30
        slow-call-rate-threshold: 30

management:
  health:
    circuitbreakers:
      enabled: true
  endpoint:
    shutdown:
      enabled: true
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
