server:
  port: 0

spring:
  application:
    name: coupon-service

  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/coupon_db
    username: root

  kafka:
    bootstrap-servers: localhost:29092
    producer:
      acks: 1

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    
  client:
    eureka-server-port: 8761
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:${eureka.client.eureka-server-port}/eureka
    healthcheck:
      enabled: true

redis:
  streams:
    name: issued-coupons-stream
    consumer:
      group: coupon-service-consumer-group
      name: coupon-service-consumer

jwt:
  issuer: auth-service
  secret_key: cPlFdV3BdHxqABIwNpgvyOkZgskfj23jeJNxjujgQoE=